title: "[Role] "
body:
  - type: markdown
    attributes:
      value: |
        ## 👥 팀원 역할 정의
        프로젝트에서 각자 담당하고 있는 파트와 세부 역할을 작성해 주세요.

  - type: textarea
    id: member-1
    attributes:
      label: "김진도"
      value: |
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: member-2
    attributes:
      label: "백승재"
      value: |
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: member-3
    attributes:
      label: "이채연"
      value: |
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: member-4
    attributes:
      label: "이하연"
      value: |
        - [ ] 
    validations:
      required: true
