title: "[Role] "
body:
  - type: markdown
    attributes:
      value: |
        ## 👥 팀원 역할 정의
        프로젝트에서 각자 담당하고 있는 파트와 세부 역할을 작성해 주세요.
  - type: textarea
    id: role-assignment
    attributes:
      label: "역할 및 담당자"
      description: "아래 양식에 맞춰 4명의 이름과 담당 파트를 작성해 주세요."
      value: |
        이름
        - [ ] 
        
        이름
        - [ ] 
        
        이름
        - [ ] 
        
        이름
        - [ ] 
    validations:
      required: true
